print("Bienvenido a la Calculadora!!")
print("1.- Suma.")
print("2.- Resta.")
print("3.- Multiplicación.")
print("4.- División.")
print("0.- Salir")
opcion = int(input("Que desea hacer?: "))
while opcion != 0:
    if opcion == 1:
        print("----Suma----")
        num1 = int(input("Ingrese Número 1: "))
        num2 = int(input("Ingrese Número 2: "))
        print(f"El resultado es {(num1 + num2)}")
        print("¿Desea alguna otra operacion?: ")
        print("1.- Suma.")
        print("2.- Resta.")
        print("3.- Multiplicación.")
        print("4.- División.")
        print("0.- Salir")
        opcion = int(input())
    elif opcion == 2:
        print("----Resta----")
        num1 = int(input("Ingrese Número 1: "))
        num2 = int(input("Ingrese Número 2: "))
        print(f"El resultado es {(num1 - num2)}")
        print("¿Desea alguna otra operacion?")
        print("1.- Suma.")
        print("2.- Resta.")
        print("3.- Multiplicación.")
        print("4.- División.")
        print("0.- Salir")
        opcion = int(input())
    elif opcion == 3:
        print("----Multiplicación----")
        num1 = int(input("Ingrese Número 1: "))
        num2 = int(input("Ingrese Número 2: "))
        print(f"El resultado es {(num1 * num2)}")
        print("¿Desea alguna otra operacion?")
        print("1.- Suma.")
        print("2.- Resta.")
        print("3.- Multiplicación.")
        print("4.- División.")
        print("0.- Salir")
        opcion = int(input())
    elif opcion == 4:
        print("----División----")
        num1 = int(input("Ingrese Número 1: "))
        num2 = int(input("Ingrese Número 2: "))
 #      if num2 == 0:
        while num2 == 0:
            print(f"No puede DIVIDIR POR 0 (CERO))\nIngrese el numero 2 nuevamente")
            num2 = int(input())
        print(f"El resultado es: {num1/num2}")
        print("¿Desea alguna otra operacion?")
        print("1.- Suma.")
        print("2.- Resta.")
        print("3.- Multiplicación.")
        print("4.- División.")
        print("0.- Salir")
        opcion = int(input())
print("Adiós!")
         
